<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-19T21:26:11 IST" name="Default suite" finished-at="2022-07-19T21:26:32 IST" duration-ms="20845">
    <groups>
    </groups>
    <test started-at="2022-07-19T21:26:11 IST" name="Default test" finished-at="2022-07-19T21:26:32 IST" duration-ms="20845">
      <class name="assignmentAllSeleniumAdvanced.NewTest11">
        <test-method is-config="true" signature="startTest()[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:11 IST" name="startTest" finished-at="2022-07-19T21:26:12 IST" duration-ms="959" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTest -->
        <test-method signature="Register(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:12 IST" name="Register" data-provider="myTestData1" finished-at="2022-07-19T21:26:26 IST" duration-ms="14272" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Kann1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Kann1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[kanza5@gmail.com]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[test1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [kanza5@gmail.com] but found [My account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [kanza5@gmail.com] but found [My account]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at assignmentAllSeleniumAdvanced.NewTest11.Register(NewTest11.java:110)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Register -->
        <test-method is-config="true" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:26 IST" name="captureStatus" finished-at="2022-07-19T21:26:27 IST" duration-ms="269" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Register status=FAILURE method=NewTest11.Register(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:27 IST" name="login" data-provider="myTestData" finished-at="2022-07-19T21:26:30 IST" duration-ms="2989" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[kanza5123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[test1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [kanza5123@gmail.com] but found [My account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [kanza5123@gmail.com] but found [My account]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at assignmentAllSeleniumAdvanced.NewTest11.login(NewTest11.java:128)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="captureStatus(org.testng.ITestResult)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:30 IST" name="captureStatus" finished-at="2022-07-19T21:26:30 IST" duration-ms="333" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=FAILURE method=NewTest11.login(java.lang.String,java.lang.String)[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- captureStatus -->
        <test-method is-config="true" signature="endTest1()[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:30 IST" name="endTest1" finished-at="2022-07-19T21:26:31 IST" duration-ms="767" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest1 -->
        <test-method is-config="true" signature="endTest()[pri:0, instance:assignmentAllSeleniumAdvanced.NewTest11@788ddc1f]" started-at="2022-07-19T21:26:31 IST" name="endTest" finished-at="2022-07-19T21:26:32 IST" duration-ms="1096" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- assignmentAllSeleniumAdvanced.NewTest11 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
